import type { FindWidgetState } from '../FindWidgetState/FindWidgetState.ts'
import * as FocusSource from '../FocusSource/FocusSource.ts'

export const createDefaultState = (): FindWidgetState => {
  return {
    ariaAnnouncement: '',
    editorHeight: 0,
    editorUid: 0,
    editorWidth: 0,
    editorX: 0,
    editorY: 0,
    focus: 0,
    focused: false,
    focusSource: FocusSource.Unknown,
    height: 0,
    history: [],
    inputBorderWidth: 1,
    inputErrorMessage: '',
    inputGap: 3,
    inputLineHeight: 24,
    inputPaddingBottom: 2,
    inputPaddingTop: 2,
    inputSource: 0,
    lines: [],
    matchCase: false,
    matchCount: 0,
    matches: new Uint32Array(),
    matchIndex: -1,
    matchWholeWord: false,
    minWidth: 300,
    preserveCase: false,
    replaceExpanded: false,
    replacement: '',
    resizerPointerDown: false,
    searchInputHeight: 24,
    selections: [],
    uid: 0,
    useRegularExpression: false,
    value: '',
    version: 0,
    width: 0,
    x: 0,
    y: 0,
  }
}
