export const MatchCase = 'CaseSensitive'
export const UseRegularExpression = 'Regex'
export const MatchWholeWord = 'WholeWord'
export const ArrowDown = 'ArrowDown'
export const ArrowUp = 'ArrowUp'
export const Close = 'Close'
export const Replace = 'Replace'
export const ReplaceAll = 'ReplaceAll'
